# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/flyrank-bih/flyrank-ml-internship-starter/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task

**Task type: Scoring**

My ML task is to assign each page an opportunity score that represents how much attention the page may need from the SEO/content team.

The score will help us rank pages from higher-priority opportunities to lower-priority opportunities. The main action supported by this output is deciding which pages should be reviewed or improved first.

I am framing this as a scoring problem because the goal is not only to predict whether a page has an issue, but to estimate and prioritize the relative opportunity across many pages.## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

In [13]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Target or proxy

The ideal target would be the future improvement a page gets after an SEO or content change, such as an increase in organic clicks or traffic. However, this future outcome is not available in the starter data.

Therefore, I will use a proxy target: a page opportunity score.

The proxy represents the relative level of opportunity for each page based on the available page and search-performance signals. A higher score would indicate that the page should receive higher priority for review.

This is a proxy rather than a true outcome because it does not directly measure the improvement caused by a future content change.## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

In [14]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Success metric

The main success metric will be Precision@K, where K represents the number of top-ranked pages that the content or SEO team can realistically review.

Precision@K measures how many of the top K pages identified by the model are genuinely useful opportunities.

This metric fits the task because the main goal is to create a useful priority list rather than make a binary prediction for every page. A high Precision@K would mean that the pages placed near the top of the review queue are more likely to be valuable opportunities.

The current starter data does not contain verified future outcomes, so Precision@K cannot be calculated yet. It would be evaluated later when labeled outcomes or human-reviewed opportunity labels are available.## 3. Success metric

*One metric you can defend. What number means 'good'?*

In [15]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. The unit of analysis, as a real dataframe

The unit of analysis is a content/page record.

Each row represents one page or content item associated with a client. The `content_id` identifies the page record, while `client_id` identifies the client associated with it.

This is the appropriate unit of analysis because the ML output will eventually be used to score and prioritize individual pages for SEO/content review.

The starter dataset contains 30,000 page records and 44 columns.## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [16]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
!git clone https://github.com/flyrank-bih/flyrank-ml-internship-starter.git

fatal: destination path 'flyrank-ml-internship-starter' already exists and is not an empty directory.

In [17]:
import pandas as pd

data_path = "flyrank-ml-internship-starter/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(data_path)

print("Shape:", df.shape)

df.head()

Shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [18]:
print("Shape:", df.shape)
print("Columns:")
print(df.columns.tolist())

df.head()

Shape: (30000, 44)
Columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [19]:
df[[
    "content_id",
    "client_id",
    "search_volume",
    "content_type",
    "main_intent"
]].head(10)

,content_id,client_id,search_volume,content_type,main_intent
0,content_304f48230142,client_f369cb89fc,10.0,keyword article,transactional
1,content_a1fb4e703a9e,client_4e07408562,90.0,keyword article,informational
2,content_9aa793d4d895,client_7f2253d7e2,0.0,keyword article,informational
3,content_331d6c4de07b,client_19581e27de,10.0,keyword article,commercial
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,keyword article,informational
5,content_d4084a4bc775,client_f369cb89fc,720.0,keyword article,transactional
6,content_9a34b442b552,client_8722616204,0.0,keyword article,informational
7,content_a63219c6e95a,client_19581e27de,590.0,keyword article,commercial
8,content_5e6c160719bc,client_6208ef0f77,0.0,keyword article,informational
9,content_c27558df2b0c,client_19581e27de,0.0,keyword article,informational

In [20]:
target_sketch = df[["content_id"]].head(10).copy()

target_sketch["opportunity_score"] = None

target_sketch

             content_id opportunity_score
0  content_304f48230142              None
1  content_a1fb4e703a9e              None
2  content_9aa793d4d895              None
3  content_331d6c4de07b              None
4  content_d99b7a2d90ca              None
5  content_d4084a4bc775              None
6  content_9a34b442b552              None
7  content_a63219c6e95a              None
8  content_5e6c160719bc              None
9  content_c27558df2b0c              None

## 5. Why ML beats a fixed rule here

ML is useful here because it can learn relationships among multiple page-level signals rather than relying on one manually selected threshold. Whether this produces better prioritization should be tested using the chosen evaluation metric, Precision@K.

In [21]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 6. Self-check

- [x] I identified the ML task type as scoring.
- [x] I defined a target/proxy as a page opportunity score.
- [x] I selected Precision@K as the success metric.
- [x] I showed the unit of analysis using a real dataframe.
- [x] I identified one row as one content/page record.
- [x] I explained why multiple page-level signals make a learned approach useful compared with a single fixed rule.
- [x] I connected the model output to a real content action: prioritizing pages for SEO/content review.
- [x] I noted that the current data does not provide verified future outcomes, so the opportunity score is a proxy and Precision@K cannot yet be directly evaluated.## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.